CREATE TABLE IF NOT EXISTS sources (
  id varchar(36) PRIMARY KEY,
  name varchar(255) NOT NULL,
  source_type varchar(64) NOT NULL,
  location text,
  owner_actor_id varchar(128) NOT NULL DEFAULT 'local-owner',
  sensitivity varchar(64) NOT NULL DEFAULT 'internal',
  trust_level varchar(64) NOT NULL DEFAULT 'unreviewed',
  enabled boolean NOT NULL DEFAULT true,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS collection_runs (
  id varchar(36) PRIMARY KEY,
  source_id varchar(36) REFERENCES sources(id),
  status varchar(64) NOT NULL DEFAULT 'created',
  dry_run boolean NOT NULL DEFAULT true,
  requested_by_actor_id varchar(128) NOT NULL DEFAULT 'local-owner',
  summary_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS raw_artifacts (
  id varchar(36) PRIMARY KEY,
  source_id varchar(36) REFERENCES sources(id),
  collection_run_id varchar(36) REFERENCES collection_runs(id),
  content_hash varchar(128) NOT NULL,
  storage_path text NOT NULL,
  mime_type varchar(255),
  size_bytes integer,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS normalized_documents (
  id varchar(36) PRIMARY KEY,
  raw_artifact_id varchar(36) REFERENCES raw_artifacts(id),
  source_id varchar(36) REFERENCES sources(id),
  title varchar(255),
  document_type varchar(64) NOT NULL DEFAULT 'unknown',
  language varchar(32),
  text_content text NOT NULL,
  sensitivity varchar(64) NOT NULL DEFAULT 'internal',
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS chunks (
  id varchar(36) PRIMARY KEY,
  document_id varchar(36) NOT NULL REFERENCES normalized_documents(id),
  chunk_index integer NOT NULL,
  text_content text NOT NULL,
  location_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  embedding_status varchar(64) NOT NULL DEFAULT 'not_started',
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS evidence_items (
  id varchar(36) PRIMARY KEY,
  source_id varchar(36) REFERENCES sources(id),
  document_id varchar(36) REFERENCES normalized_documents(id),
  chunk_id varchar(36) REFERENCES chunks(id),
  evidence_type varchar(64) NOT NULL,
  statement text NOT NULL,
  observed_at timestamptz,
  confidence integer,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS work_items (
  id varchar(36) PRIMARY KEY,
  work_type varchar(64) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'queued',
  requested_by_actor_id varchar(128) NOT NULL DEFAULT 'local-owner',
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS audit_events (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  actor_id varchar(128) NOT NULL DEFAULT 'system',
  event_type varchar(128) NOT NULL,
  decision varchar(64),
  resource_type varchar(64),
  resource_id varchar(128),
  correlation_id varchar(128),
  details_json jsonb NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS patterns (
  id varchar(36) PRIMARY KEY,
  pattern_type varchar(64) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'proposed',
  summary text,
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence integer,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS hypotheses (
  id varchar(36) PRIMARY KEY,
  hypothesis_text text NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'proposed',
  supporting_evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  missing_evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  confidence integer,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS predictions (
  id varchar(36) PRIMARY KEY,
  prediction_text text NOT NULL,
  expected_result text,
  disproof_condition text,
  status varchar(64) NOT NULL DEFAULT 'proposed',
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence integer,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS recommendations (
  id varchar(36) PRIMARY KEY,
  recommendation_text text NOT NULL,
  risk_level varchar(64),
  approval_required boolean NOT NULL DEFAULT false,
  expected_result text,
  status varchar(64) NOT NULL DEFAULT 'proposed',
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence integer,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS claims (
  id varchar(36) PRIMARY KEY,
  claim_text text NOT NULL,
  claim_type varchar(64),
  status varchar(64) NOT NULL DEFAULT 'proposed',
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  confidence integer,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS approvals (
  id varchar(36) PRIMARY KEY,
  request_type varchar(64) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'pending',
  requested_by_actor_id varchar(128) NOT NULL,
  decided_by_actor_id varchar(128),
  decision_reason text,
  request_payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  decided_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS feedback_events (
  id varchar(36) PRIMARY KEY,
  target_type varchar(64) NOT NULL,
  target_id varchar(128) NOT NULL,
  label varchar(64),
  actor_id varchar(128) NOT NULL DEFAULT 'local-owner',
  note text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS outcomes (
  id varchar(36) PRIMARY KEY,
  target_type varchar(64) NOT NULL,
  target_id varchar(128) NOT NULL,
  outcome_status varchar(64) NOT NULL,
  summary text,
  occurred_at timestamptz,
  evidence_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS improvement_items (
  id varchar(36) PRIMARY KEY,
  target_area varchar(128) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'proposed',
  objective text,
  proposed_by_actor_id varchar(128) NOT NULL DEFAULT 'local-owner',
  priority integer DEFAULT 0,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS experiment_runs (
  id varchar(36) PRIMARY KEY,
  improvement_item_id varchar(36) REFERENCES improvement_items(id),
  status varchar(64) NOT NULL DEFAULT 'proposed',
  mlflow_run_id varchar(128),
  optuna_study_name varchar(128),
  metrics_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  artifacts_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS reports (
  id varchar(36) PRIMARY KEY,
  title varchar(255) NOT NULL,
  report_type varchar(64) NOT NULL,
  status varchar(64) NOT NULL DEFAULT 'draft',
  requested_by_actor_id varchar(128) NOT NULL DEFAULT 'local-owner',
  artifact_path text,
  metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);